### PR TITLE
#1164 Make sure that all import types of a Type are imported for the wrapper

### LINKED ISSUE #1164: Missing import when using generic on generic element
My class **SearchResultDto** contains this attribute
`  private List<GenericRessource<CriteriaDto>> criterias;`

i have a mapper like this 

```
@Mapper(componentModel = "spring", uses = {CriteriaWsMapper.class, .....(other classes)})
public abstract class SearchResultWsMapper extends GenericWsMapper<SearchResult, SearchResultDto> {
....
}
```
this  mapper works fine with mapstructure 1.0.0.Final and generates this file 

```
package mydomain.ws.mappers;

import mydomain.domain.entities.SearchResult;
import mydomain.ws.dto.SearchResultDto;
import javax.annotation.Generated;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2017-03-30T16:27:59+0200",
    comments = "version: 1.0.0.Final, compiler: javac, environment: Java 1.8.0_121 (Oracle Corporation)"
)
@Component
public class SearchResultWsMapperImpl extends SearchResultWsMapper {

    @Autowired
    private PieceWsMapper pieceWsMapper;
    @Autowired
    private CapaciteWsMapper capaciteWsMapper;
    @Autowired
    private ArgumentaireHuileWsMapper argumentaireHuileWsMapper;

    @Override
    public SearchResultDto toDto(SearchResult entity) {
        if ( entity == null ) {
            return null;
        }

        SearchResultDto searchResultDto = new SearchResultDto();

        searchResultDto.setCriterias( mapCriterias( entity.getCriterias() ) );
        searchResultDto.setGroupePieces( mapGroup( entity.getGroupePieces() ) );
        searchResultDto.setAfficherAvertissement( entity.isAfficherAvertissement() );
        searchResultDto.setPiecesAssociees( pieceWsMapper.toDtos( entity.getPiecesAssociees() ) );
        searchResultDto.setCapaciteVariantes( capaciteWsMapper.toDtos( entity.getCapaciteVariantes() ) );
        searchResultDto.setArgumentairesHuiles( argumentaireHuileWsMapper.toDtos( entity.getArgumentairesHuiles() ) );

        return searchResultDto;
    }
}

```

when i try to migrate to 1.1.0.Final the generated file is :

```
package mydomain.ws.mappers;

import mydomain.domain.entities.SearchResult;
import mydomain.ws.GenericRessource;
import mydomain.ws.dto.ArgumentaireHuileDto;
import mydomain.ws.dto.CapaciteVarianteDto;
import mydomain.ws.dto.GroupePieceDto;
import mydomain.ws.dto.PieceDto;
import mydomain.ws.dto.SearchResultDto;
import java.util.List;
import javax.annotation.Generated;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2017-03-30T16:29:18+0200",
    comments = "version: 1.1.0.Final, compiler: javac, environment: Java 1.8.0_121 (Oracle Corporation)"
)
@Component
public class SearchResultWsMapperImpl extends SearchResultWsMapper {

    @Autowired
    private PieceWsMapper pieceWsMapper;
    @Autowired
    private CapaciteWsMapper capaciteWsMapper;
    @Autowired
    private ArgumentaireHuileWsMapper argumentaireHuileWsMapper;

    @Override
    public SearchResultDto toDto(SearchResult entity) {
        if ( entity == null ) {
            return null;
        }

        SearchResultDto searchResultDto = new SearchResultDto();

        List<GenericRessource<CriteriaDto>> list = mapCriterias( entity.getCriterias() );
        if ( list != null ) {
            searchResultDto.setCriterias( list );
        }
        List<GroupePieceDto> list_ = mapGroup( entity.getGroupePieces() );
        if ( list_ != null ) {
            searchResultDto.setGroupePieces( list_ );
        }
        searchResultDto.setAfficherAvertissement( entity.isAfficherAvertissement() );
        List<PieceDto> list__ = pieceWsMapper.toDtos( entity.getPiecesAssociees() );
        if ( list__ != null ) {
            searchResultDto.setPiecesAssociees( list__ );
        }
        List<CapaciteVarianteDto> list___ = capaciteWsMapper.toDtos( entity.getCapaciteVariantes() );
        if ( list___ != null ) {
            searchResultDto.setCapaciteVariantes( list___ );
        }
        List<ArgumentaireHuileDto> list____ = argumentaireHuileWsMapper.toDtos( entity.getArgumentairesHuiles() );
        if ( list____ != null ) {
            searchResultDto.setArgumentairesHuiles( list____ );
        }

        return searchResultDto;
    }
}

```

it does not compile and there is a missing import for the class CriteriaDto

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #1164

### CODE REVIEW

**Comment by agudian** [comment]
👍

**Comment by filiphr** [comment]
Thanks for the review @agudian. Once the build is done I will merge it. Can you also have a look at the issue. It looks like the code generated in 1.0.0.Final is not the same as in 1.1.0.Final, and I am not sure what is correct :). It looks like for `Collection`(s) and `Map`(s) we are not setting them to `null` if the source is `null`.

**Comment by agudian** [comment]
> It looks like for Collection(s) and Map(s) we are not setting them to null if the source is null.

I think Sjaak fixed some stuff there and the change was intentional (didn't we even have something about that in the migration notes?)...

**Comment by filiphr** [comment]
@agudian Thanks again for the review. I have merged it to master

**Pull request merged**
