### PR TITLE
 #1914 Remove unused method Type.isAnnotatedWith

### LINKED ISSUE #1914: Refactoring class Type
There is unused method Type.isAnnotatedWith and some big methods in the class Type. Should we remove this method and to do some refactoring?

### PR DESCRIPTION
**Pull request by Captain1653**
Fixes #1914

### CODE REVIEW

**Comment by Captain1653** [comment]
> The removal of `isAnnotatedWith` is ok for me. However, the split for the other methods not really. Why is it bad to have a bigger method? Was it complex to follow it what is happening?

Honestly, It was little complex for me. I thought it can be little more readable, but I can revert splitted method and replaced with Stream API if it necessary.

**Comment by filiphr** [comment]
I would prefer the previous non split method. As for replacing it with Stream API, I doubt that it would make it more readable. Stream is not always better :)

**Comment by Captain1653** [comment]
@filiphr Ok, I have fixed it.

**Comment by filiphr** [comment]
Thanks, feel free to merge when you can

**Comment by Captain1653** [comment]
Thanks for review @sjaakd and @filiphr

**Pull request merged**
