### PR TITLE
Remove redundant null checks in nested properties

### LINKED ISSUE #3245: Redundant null checks for nested properties
### Expected behavior

Consider this simple DTO and Entity classes:

```java
@Data
public class PersonDTO {
    private String name;
    private String parentName;
}
```

```java
@Data
public class Person {
    private String name;
    private Person parent;
}
```

And a simple mapper:

```java
@Mapper
public interface PersonMapper {

    @Mapping(target = "parentName", source = "parent.name")
    PersonDTO entityToDTO(Person person);
}
```

Generated code should be:

```java
public class PersonMapperImpl implements PersonMapper {

    @Override
    public PersonDTO entityToDTO(Person person) {
        if ( person == null ) {
            return null;
        }

        PersonDTO personDTO = new PersonDTO();

        personDTO.setParentName( personParentName( person ) );
        personDTO.setName( person.getName() );

        return personDTO;
    }

    private String personParentName(Person person) {
        Person parent = person.getParent();
        if ( parent == null ) {
            return null;
        }
        return parent.getName();
    }
```

### Actual behavior

Generated code is this:

```java
public class PersonMapperImpl implements PersonMapper {

    @Override
    public PersonDTO entityToDTO(Person person) {
        if ( person == null ) {
            return null;
        }

        PersonDTO personDTO = new PersonDTO();

        personDTO.setParentName( personParentName( person ) );
        personDTO.setName( person.getName() );

        return personDTO;
    }

    private String personParentName(Person person) {
        if ( person == null ) {       // Redundant null check, unreachable return statement
            return null;
        }
        Person parent = person.getParent();
        if ( parent == null ) {
            return null;
        }
        String name = parent.getName();
        if ( name == null ) {      // Redundant null check, just return the parent name
            return null;
        }
        return name;
    }
```

As marked, two additional redundant null checks were generated. The first one makes it impossible to reach full code coverage (unless using Reflection) and the second is just unnecessary code.

### Steps to reproduce the problem

No special configuration needed to reproduce this.

### MapStruct Version

MapStruct 1.5.4.Final

### PR DESCRIPTION
**Pull request by jccampanero**
The code changes provided try removing redundant null checks for nested properties.

Fixes #3245.

### CODE REVIEW

**Review by filiphr — COMMENTED** [review]
Thanks for the work on this @jccampanero.

I think that there might be situations where this does not work as it should. Can we add test cases for that perhaps:

* Using nested source with a `NullValueMappingStrategy.RETURN_DEFAULT`
* Have a presence check / condition check for the last element in the nesting

**Comment by jccampanero** [comment]
You are welcome @filiphr, I just tried to work in some of the planned issues as you mentioned, although I understand this issue is not planned for the 1.6 release; I appreciate that even in that case you reviewed the code, thank you very much for the feedback.

I tested the code with a `NullValueMappingStrategy.RETURN_DEFAULT` in fact and I think it is working properly, it compiles, and the generated mappings look fine. For instance, for this DTO:

```java
public class PersonDTO {
    private String name;
    private PersonDTO parent;
    private PersonDTO grandParent;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public PersonDTO getParent() {
        return parent;
    }

    public void setParent(PersonDTO parent) {
        this.parent = parent;
    }

    public PersonDTO getGrandParent() {
        return grandParent;
    }

    public void setGrandParent(PersonDTO grandParent) {
        this.grandParent = grandParent;
    }
}
```

and entity:

```java
public class Person {
    private String name;
    private Person parent;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Person getParent() {
        return parent;
    }

    public void setParent(Person parent) {
        this.parent = parent;
    }
}
```

for this `Mapper`:

```java
@Mapper(
        nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT
)
public interface PersonMapper {

    @Mapping(target = "grandParent", source = "parent.parent")
    PersonDTO entityToDTO(Person person);
}
```

it generates:

```java
package org.mapstruct.ap.test.nestedproperties.redundantNulls;

import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-05-20T17:29:04+0200",
    comments = "version: , compiler: javac, environment: Java 11.0.19 (Ubuntu)"
)
public class PersonMapperImpl implements PersonMapper {

    @Override
    public PersonDTO entityToDTO(Person person) {

        PersonDTO personDTO = new PersonDTO();

        if ( person != null ) {
            personDTO.setGrandParent( entityToDTO( personParentParent( person ) ) );
            personDTO.setName( person.getName() );
            personDTO.setParent( entityToDTO( person.getParent() ) );
        }

        return personDTO;
    }

    private Person personParentParent(Person person) {
        Person parent = person.getParent();
        if ( parent == null ) {
            return null;
        }
        return parent.getParent();
    }
}
```

Please, in any case, can you propose a test case that you think could fail? I will work on it as necessary.

Please, could you elaborate the idea behind the last presence check as well? Could you provide a skeleton of the test case necessary to test that functionally? I will expand and test it with glad.

**Comment by MrDolch** [comment]
How to restart the build which got a timeout on external resource?
https://github.com/mapstruct/mapstruct/actions/runs/4969138586/jobs/8892141578?pr=3275

**Review by MrDolch — APPROVED** [review]
Looks good to me.

**Comment by filiphr** [comment]
@MrDolch we have some problems with the Windows build. No need to restart. We merge things when it is clear that the test failures are not related to some flakiness.

Thanks for checking the `NullValueMappingStrategy` @jccampanero, I was not sure what is being generated. It indeed seems like the first if is always obsolete.

Regarding the other test case I mentioned. What I meant is something like we

```
class Song {
    private Artist artist
}
```

**Comment by filiphr** [comment]
@jccampanero sorry I closed the PR by accident (pressed a wrong shortcut 😄). I've also updated my last comment to include the examples I wanted to include

**Comment by jccampanero** [comment]
> @jccampanero sorry I closed the PR by accident (pressed a wrong shortcut 😄)

Don't worry, don't worry,... :angry:...

Now seriously, please, don't worry @filiphr, it is perfectly fine 😃 

I reviewed the use case that you provided and I think the changes are still working, probably because of the first condition in the FreeMarker template.

I used the following POJOs:

```java
public class Artist {
    private String name;

    public boolean hasName() {
        return name != null && name.length() > 0;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

```java
public class Song {
    private Artist artist;

    public Artist getArtist() {
        return artist;
    }

    public void setArtist(Artist artist) {
        this.artist = artist;
    }
}
```

```java
public class SongDTO {
    private String artistName;

    public String getArtistName() {
        return artistName;
    }

    public void setArtistName(String artistName) {
        this.artistName = artistName;
    }
}
```

the following mapper definition:

```java
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface SongMapper {

    SongMapper INSTANCE = Mappers.getMapper( SongMapper.class );

    @Mapping(target = "artistName", source = "artist.name")
    SongDTO map(Song song);
}
```

and this test case:

```java
mport org.mapstruct.ap.testutil.ProcessorTest;
import org.mapstruct.ap.testutil.WithClasses;

import static org.assertj.core.api.Assertions.assertThat;

public class SongMapperTest {

    @ProcessorTest
    @WithClasses({Artist.class, Song.class, SongDTO.class, SongMapper.class})
    void shouldDealWithPresenceCheckInABackwardCompatibleWay() {
        Artist artist = new Artist();
        artist.setName("");
        Song song = new Song();
        song.setArtist(artist);

        SongDTO songDTO = SongMapper.INSTANCE.map(song);

        assertThat(songDTO.getArtistName()).isNull();
    }

    @ProcessorTest
    @WithClasses({Artist.class, Song.class, SongDTO.class, SongMapper.class})
    void shouldBehaveCorrectly() {
        Artist artist = new Artist();
        String artistName = "U2";
        artist.setName(artistName);
        Song song = new Song();
        song.setArtist(artist);

        SongDTO songDTO = SongMapper.INSTANCE.map(song);

        assertThat(songDTO.getArtistName()).isEqualTo(artistName);
    }
}
```

and it seems to work property.

The generated mapper looks like this:

```java
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-05-21T23:54:42+0200",
    comments = "version: , compiler: javac, environment: Java 11.0.19 (Ubuntu)"
)
public class SongMapperImpl implements SongMapper {

    @Override
    public SongDTO map(Song song) {
        if ( song == null ) {
            return null;
        }

        SongDTO songDTO = new SongDTO();

        songDTO.setArtistName( songArtistName( song ) );

        return songDTO;
    }

    private String songArtistName(Song song) {
        Artist artist = song.getArtist();
        if ( artist == null ) {
            return null;
        }
        if ( artist == null || !artist.hasName() ) {
            return null;
        }
        return artist.getName();
    }
}
```

Maybe I'm forgetting something?

**Comment by filiphr** [comment]
Thanks for checking it @jccampanero. Really nice improvement. Thanks for working on it

**Comment by jccampanero** [comment]
You're welcome @filiphr, my pleasure.  I hope that in the end there won't be any use case where the new code would lead to an error. I will pay attention to that.

**Pull request merged**
