### PR TITLE
Fix leaking test classloader

### LINKED ISSUE #338: Unit test leaks classes from @WithClasses
To demonstrate this, just add:

```java
   @Test
    @WithClasses({ ArtistToChartEntryAdder.class, ChartPositions.class, AdderUsageObserver.class })
    public void shouldUseGetAsTargetAccessor2() {

        AdderUsageObserver.setUsed( false );
        Song song = new Song();
        song.setPositions( Arrays.asList( 3, 5 ) );

        Chart chart = new Chart();
        chart.setSong( song );

        ChartPositions positions = ArtistToChartEntryGetter.MAPPER.map( chart );
        assertThat( positions ).isNotNull();
        assertThat( positions.getPositions() ).containsExactly( 3L, 5L );

        assertFalse( AdderUsageObserver.isUsed() );
    }
```

As last method to the unit test: `org.mapstruct.ap.test.nestedsourceproperties.NestedSourcePropertiesTest`.

Note: `ArtistToChartEntryAdder` is added to the `@WithClasses` while `ArtistToChartEntryGetter` is actually used. Presumably `ArtistToChartEntryAdder` 'leaks' from the previous method.

### PR DESCRIPTION
**Pull request by agudian**
Fixes #338.

### CODE REVIEW

**Comment by agudian** [comment]
@sjaakd / @gunnarmorling: does either one of you want to take a rough look at this before I merge it? Say no if you like :wink:.

What I've changed, basically, is that I now create a fresh new classloader whenever the set of Classes to be compiled for a method changes. With that comes the need to replace the test class (in TestClass) with a new one loaded freshly from the new classloader (while rebasing I've changed that to use a delegate to TestClass that is replaced when required).
That wouldn't have been possible in JUnit 4.11 without having to copy/paste a lot of code from JUnit (thank you, protected final methods).

**Comment by sjaakd** [comment]
Hey @agudian .. I was just working on this one.. But I'm finding it kind of hard. So thanks for the explanation. ;).

**Comment by sjaakd** [comment]
As far as I can judge.. Merge please :smile:..

**Comment by agudian** [comment]
Merged, thanks for the review! :+1:

**Comment by gunnarmorling** [comment]
Do you guys see any commits/files at this PR? I don't, maybe it's an issue with GitHub?

**Pull request closed without merging**
