### PR TITLE
#2164 parameter matching should be done based on name when source name is absent

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by sjaakd** [comment]
@filiphr .. any idea why the integration tests fails.. ? I'm quite puzzled..

**Comment by filiphr** [comment]
It is failing because the test is named incorrectly. It is named `Issue2164Tester.java` and it should be named `Issue2164Test.java`. I also suspect that it is not picked up by the maven surefire plugin for the normal tests as well

**Comment by sjaakd** [comment]
> It is failing because the test is named incorrectly. It is named `Issue2164Tester.java` and it should be named `Issue2164Test.java`. I also suspect that it is not picked up by the maven surefire plugin for the normal tests as well

Ah.. I completely looked over that..

I think BTW that we should refactor this.. I guess that during the construction of `SourceReference` we should already cater for the fact that `source` has the same name as `target`.. This should not be solved in `beanmapping`

WDYT..?

**Comment by filiphr** [comment]
I think that `beanMapping` is the correct place for this. However, I think that we need to do a solution like we are doing in `applyPropertyNameBasedMapping` and `applyParameterNameBasedMapping`, also with the error handling. Because when there are multiple source parameters and both have a property named in the same way then you have to defined the source parameter. Currently we will pick the property from the first source parameter, which is not the same if you don't define it.

I would say that the "// its a plain-old property mapping" `else` should be refactored to use the same logic as `applyPropertyNameBasedMapping` and `applyParameterNameBasedMapping`. You can even add a test with and without `@Mapping` to verify that the output is the same.

**Comment by sjaakd** [comment]
> I think that `beanMapping` is the correct place for this. However, I think that we need to do a solution like we are doing in `applyPropertyNameBasedMapping` and `applyParameterNameBasedMapping`, also with the error handling. Because when there are multiple source parameters and both have a property named in the same way then you have to defined the source parameter. Currently we will pick the property from the first source parameter, which is not the same if you don't define it.
> 
> I would say that the "// its a plain-old property mapping" `else` should be refactored to use the same logic as `applyPropertyNameBasedMapping` and `applyParameterNameBasedMapping`. You can even add a test with and without `@Mapping` to verify that the output is the same

I guess we need to distinguish between:
1. Where
2. When

1. Where: I think that deriving all the segments in "SourceReference" and "TargetReferences" is in the right spot, from an separation of concerns perspective. We should not overload bean mapping with that kind of functionality. So I would assume that when we derive all the segments, we should also take into consideration that the name of target should be used (when the source name is absent). That's more what I meant.

2. when: I agree completely with you that deriving the correctness of the segments in relation to forged- or existing methods is done at the wrong moment.

I did look into merging name-based and defined parameters in one method but always gave up 😄 . But, I guess it would not harm to try again..

**Comment by sjaakd** [comment]
@filiphr on a general note: I don't want to go into refactoring in this solution. It's just that I concluded the logic needs to be there, but can be done in refactored way, making it less brittle. Hence i referred to the refactoring.

**Pull request merged**
