### PR TITLE
#2773 feat: Copy the method annotation to the implementation method

### PR DESCRIPTION
**Pull request by chenzijia12300**
I tried to implement it as it is in [#2773](https://github.com/mapstruct/mapstruct/issues/2773).
this is my first time submitting code for an open source project, I hope it works, if there is anything wrong, I will improve it

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks for raising this PR @chenzijia12300. We currently have PR #2792 which is doing an extensive changes in our implementation and how we handle passing annotations to the generated methods. Once this PR is merged, we are going to be able to look into this PR and #2773

**Comment by chenzijia12300** [comment]
I've looked at your implementation of annotation passing, and it feels much better than mine, and I'm looking forward to the final result of [#2792](https://github.com/mapstruct/mapstruct/pull/2792) 😊

**Comment by filiphr** [comment]
@chenzijia12300 we've finally merged #2792 into main. Are you interested in trying to add the functionality of #2773 on top of what we added on main? I think that for now we should only copy the `@Deprecated` annotations and leave the rest untouched. People can use `@AnnotateWith` if they want to pass some other annotations to the implementation

**Comment by chenzijia12300** [comment]
Yes I am interested, thank you for the ideas 😊

**Comment by filiphr** [comment]
Great @chenzijia12300, then go for it. If you have any questions, you know where to find us 😉

**Comment by filiphr** [comment]
@chenzijia12300 I think that you pushed main into your branch and Github thought that it was merged. I got confused for a second about why this was saying that it was merged

**Comment by chenzijia12300** [comment]
(⊙﹏⊙) I don't quite understand, do I need to create a new branch and push it?

**Pull request merged**
