### PR TITLE
Rename Typo to FormattingMessenger

### PR DESCRIPTION
**Pull request by yokotaso**
I found typo class name FormattingMessager. It is FormattingMessenger, isn't it?

I renamed class name and rename field,method argument param.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hi, thanks a lot for your efforts! It was named "messager" intentionally,
though. It's named after javax.annotation.processing.Messager.

**Comment by yokotaso** [comment]
Thank you for your comment! Sorry for bother you.

**Comment by gunnarmorling** [comment]
No worries, it's much appreciated that you're interested in contributing.
If you like to hack on another issue, just have a chat with Filip what
might be a good candidate.

**Comment by filiphr** [comment]
@yokotaso you are not bothering at all. We are always glad to accept new contributions. If you want to contribute something have a look at our [issue tracker](https://github.com/mapstruct/mapstruct/issues). We also have issues labeled with [good first issue](https://github.com/mapstruct/mapstruct/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and [up-for-grabs](https://github.com/mapstruct/mapstruct/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs) that might be a starting point. Those are of course not the only ones that you can contribute to 😄. Feel free to write in any issue and we can help you out

**Pull request closed without merging**
