### PR TITLE
#556 make the implementation name configurable

### PR DESCRIPTION
**Pull request by ggtools**
Implementation of `ServiceLoader` instead of duplicating the logic in `Mappers`. Issue #472 should be able to use this new mechanism.

Details:

- Add `implSuffix` in `@Mapper` & `@MapperConfig`

- Generate a file in `META-INF/services` when a custom suffix has been
  configured

- `Mappers` use `ServiceLoader` first in order to get a mapper's
  implementation before falling back to the former method

### CODE REVIEW

**Comment by sjaakd** [comment]
@ggtools : first of all, many thanks for your PR.  I've added some remarks. 

My biggest concern is changing the retention policy on the `@Mapper` and `@MappingConfig`. We did have some discussions on that one in the past. There is a suggestion on how we could avoid that. But perhaps @gunnarmorling can shed his thoughts on this as well.

**Comment by gunnarmorling** [comment]
> @ggtools : first of all, many thanks for your PR

+1, Many thanks!

> My biggest concern is changing the retention policy on the @Mapper and @MappingConfig. We did have some discussions on that one in the past

Right, changing the retention to `RUNTIME` seems not right. See the discussion in #472, the idea is to generate file(s) which provide the binding from mapper interface to implementation type and make these mapping types discoverable using the Java service loader mechanism, i.e. by generating a file under `META-INF/services`.

E.g. the contract could look like that:

    public interface MapperFactory {
       <T> T getMapper(Class<T> mapperInterface);
    }

MapStruct would generate an implementation of this interface which knows of all mappers of a compiliation unit (i.e. JAR) and the services file. The existing `Mappers` class would use the `java.util.ServiceLoader` to locate all mapper factories present at runtime and delegate to them to find requested mappers.

**Comment by ggtools** [comment]
I agree with the discussion in #472 and I have to re-implement the same logic during the generation and at runtime. I never used `java.util.ServiceLoader` but I might have a look at it.

**Comment by ggtools** [comment]
I'm wondering how the *service* file will be generated. I guess it'll be along with mappers' implementation. That means we couldn't split in several jars classes that have been generated at the same time. I'm not really sure it'll be an actual use case but I just had this thought.

**Comment by gunnarmorling** [comment]
> That means we couldn't split in several jars classes that have been generated at the same time

The service loader mechanism can deal with several service files for the same SPI contract, all implementations from all files will be found. So we could generate one file per compilation unit (e.g. a Maven module) and the `Mappers` factory would find all implementations at runtime (e.g. in a multi-module Maven project).

**Comment by ggtools** [comment]
I'll try to work on this next week-end

**Comment by gunnarmorling** [comment]
Cool; Thanks for the heads-up. We'll do the next release today or tomorrow, but we can do a CR2 in case your change is ready e.g. next week.

**Comment by gunnarmorling** [comment]
@ggtools Any news on that one?

**Comment by ggtools** [comment]
I had a look and I need to dive into the Mapstruct generation code it'll probably take me some time. Sorry

**Comment by gunnarmorling** [comment]
>  it'll probably take me some time.

Ok, no problem. Let's schedule it for 1.1 then.

> In a nutshell when a mapper is configured with a specific prefix [...]

Yes, this sounds about right. Just let me know in case you run into any issues with that. Btw. related to this is the customization of the package where generated mappers should go (see #472), we will benefit from the same mechanism there. In fact it should be very quickly be done, once the isse at hand has been implemented.

**Comment by gunnarmorling** [comment]
Can we close this one now that #602 is there?

**Comment by gunnarmorling** [comment]
Can we close this one now that #602 is there?

**Comment by ggtools** [comment]
Sure since it is included in #602.

**Comment by ggtools** [comment]
Closing it, see in #602

**Pull request closed without merging**
