### PR TITLE
#2278 inherited property ignored entirely due to ignore on nested level

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by filiphr** [comment]
The fix looks OK. However, I think that it fixes only the specific case in #2278. 

What if instead of ignoring it we use a `constant`?

I also have a feeling that #2318 should be fixed in the same time as #2278 as those are more or less similar.

**Comment by sjaakd** [comment]
> What if instead of ignoring it we use a `constant`?

I thought about that as well. It comes down on how you see merging of properties. I'll check what the "normal" behavior is (so how we merge properties).

**Comment by sjaakd** [comment]
I guess.. in the end I flipped just 2 arguments (not properly done when refactoring) and needed to add a null check for when the source is absent (I thought about making it equal to the target  but I remember somehow that's always right, for reversing you need to specify them both, but in case of ignoreByDefault you activate individual mappings)...

**Comment by sjaakd** [comment]
Replaces #2321

**Comment by filiphr** [comment]
Thanks for doing this @sjaakd, the fix looks really simple.

One last things. Can we also add the test case from #2322? I think that it is the same problem and that this fixes that as well.

**Comment by sjaakd** [comment]
> One last things. Can we also add the test case from #2322? I think that it is the same problem and that this fixes that as well.

I'll have a look..

**Comment by sjaakd** [comment]
> One last things. Can we also add the test case from #2322? I think that it is the same problem and that this fixes that as well.

I created a test. But it still fails. The current fix is fixing stacking of inherited(reverse) properties. This seems to be a problem in our beanmapping (the reproducer does not call the logic that is fixed).

Let treat that as a separate issue. I can push the reproducer after merging this one. Perhaps you can have a look as well?

**Comment by filiphr** [comment]
Sounds good. Thanks for trying it out. Go ahead and merge this. I'll take a look at the reproducer and try to find a fix

**Comment by sjaakd** [comment]
> Sounds good. Thanks for trying it out. Go ahead and merge this. I'll take a look at the reproducer and try to find a fix

See https://github.com/mapstruct/mapstruct/pull/2341

I'm not sure whether I've got time for it today.. It seems to be located somewhere in the `BeanMapping` - nested mapping handling.

**Pull request merged**
