### PR TITLE
#3037 Enhanced composition annotation

### PR DESCRIPTION
**Pull request by chenzijia12300**
Try to implement #3037
Let `IterableMapping`,`MapMapping`,`ValueMapping`,`ValueMappings` and other annotations support the combination pattern

### CODE REVIEW

**Comment by filiphr** [comment]
@chenzijia12300 I would suggest that we simplify this PR and only focus on the support for meta annotations for `@ValueMapping` and `@ValueMappings` in a same way as it is done for `@Mapping` and `@Mappings`. I would leave the rest of the annotations as they are. The `@IterableMapping`, `@MapMapping` etc. are different type of annotations.

**Comment by chenzijia12300** [comment]
@filiphr Okay, I will make changes. (●'◡'●)
I would like to ask for @IterableMapping, @MapMapping and other non-repeatable annotations, do you think it is necessary to make it support combination?

**Comment by filiphr** [comment]
>Okay, I will make changes. (●'◡'●)

Thanks.

>I would like to ask for `@IterableMapping`, `@MapMapping` and other non-repeatable annotations, do you think it is necessary to make it support combination?

For now I don't think that we need this. I would rather wait for someone to request this feature than doing it immediately. I don't see a big benefit for it at the moment as well. There are some tricky edge cases with this as well. like what happens if you have defined it on 2 different annotations and things like that

**Comment by chenzijia12300** [comment]
@filiphr Thank you for your patience in explaining
Incidentally, I seem to have screwed up this branch, so I'm going to create a new branch to implement this feature

**Pull request closed without merging**
