### PR TITLE
#320 fixing JodaTime unit test

### PR DESCRIPTION
**Pull request by sjaakd**
I fixed this, but I'm not an expert on JodaTime. I'm a bit worried on the terminating spaces on 111 and 113 on `JodaConversionTest`

### CODE REVIEW

**Comment by sjaakd** [comment]
@timoe , can you check the unit test on line 111 and 113 in this PR? Should I add a trim somewhere?

**Comment by agudian** [comment]
I'd say the trailing whitespace is not supposed to be there, as it is also not present in the specified format.

**Comment by sjaakd** [comment]
@agudian  Thanks.. I'll fix it soon and push again

**Comment by sjaakd** [comment]
Done!

**Pull request merged**
