### PR TITLE
#836, #838 left overs reverse nested mapping

### PR DESCRIPTION
**Pull request by sjaakd**
See #836. Makes flatting (normalizing e.g. normalizing into an entity) and exploding (denormalizing into an dto) a bit more friendly by allowing usage of `@InheritInverseConfiguration`

### CODE REVIEW

**Comment by sjaakd** [comment]
Hmm.. wrong test case. Need to provide a better example. Perhaps we do need another issue to tackle non existing empty constructors. Anyway..

**Comment by sjaakd** [comment]
@agudian .. Do you see a chance to review this one still? I don't think its a dramatic one :smile:

**Comment by agudian** [comment]
Looks good, go ahead with it! :+1:

**Comment by sjaakd** [comment]
Thanks for reviewing 👍

**Pull request merged**
