### PR TITLE
#419 moving responsibility of target accessor determination to Type

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by sjaakd** [comment]
@agudian : do you have time to look at this.. I've some stacked refactorings. This is the first one.

**Comment by agudian** [comment]
Saw your comment just now and need to shut off - sorry. I'll try it tomorrow. One thing I saw while scrolling through (because I stumbled across something similar today): at one point you do CHECKSTYLE:OFF, but without doing CHECKSTYLE:ON again some lines later.
We should tweak our checkstyle config to use the annotations to suppress specific checkstyle warnings...

**Comment by sjaakd** [comment]
> Saw your comment just now and need to shut off - sorry.

No problem... Gr8 that you are willing to take a look.

> at one point you do CHECKSTYLE:OFF, but without doing CHECKSTYLE:ON again some lines later.

Ok. Or even better: they should not be happening.. One of the next PR's is resolving one of them by using the builder pattern (in `SourceMethod`).

**Comment by agudian** [comment]
Looked though it... It's good to go. :+1:

**Comment by sjaakd** [comment]
Thanks!

**Pull request merged**
