### PR TITLE
#168 allow to globally configure mappings using @GlobalMapping

### PR DESCRIPTION
**Pull request by agudian**
I had to move ```@Mapper``` and ```@MapperConfig``` to ```core``` and ```core-jdk8```, as they now require ```@GlobalMapping```, which in turn requires ```@Mapping```...

### CODE REVIEW

**Comment by agudian** [comment]
Rebased to current master... I'll start with the promised more elaborate example soon-ish.

**Comment by agudian** [comment]
@gunnarmorling, @sjaakd: Here comes the example project:

In https://github.com/agudian/mapstruct-playground, I have created a self-containing, non-working scribble of how our project at work kind of looks like. We have one base entity, and one base DTO, plus some other base entity hiearchies e.g. like that AuditableEntity.

Most of our components have one single mapper, but some more complex components and two of the "other" applications that we are doing there use single mappers for each entity or small group of entites.

As of now the main application we have has more than 480 entity classes and the same number of DTO classes. Mainly because of these UUIDs in the DTOs and these audit-properties in the AuditableEntities, we use MapStruct with ```unmappedTargetPolicy=WARN``` - but that possibly hides actual unmappable properties.

With now more than 50 developers (I guess) in three countries and four projects that are based on our framework and that use MapStruct, we just have to make using it pretty simple:
* a centralized base configuration that takes care of those mandatory settings, preferrably rule based so that it can be controlled from that central location
* a fool-proof way to apply that centralized configuration

Besides the DTO/Entity mapping, we also use MapStruct for mappings to JAXB classes (from DTO or Entities) - so there might be an additional set of centralized configuration for those mappers.

I get the argument with the comprehensability - why is the code generated in the way it is, and how many hops do I need to take to find that piece of configuration. My take on this is that in such large projects as ours, it is not necessary that everyone must understand every notion of every framework involved. In fact, with the speed they need to get things done, they can't. Usually, they check how some specific thing is done in that other place and do it likewise. 

If only 10-20% of the developers in larger project understand why a certain property doesn't need to be explicitly ignored, or what that base-configuration does, then that's totally ok, IMHO. The odds are probably different in small projects - but then again, if one of the developers ask himself that question, then I can give an answer to that with two lines of text via instant messanger. For everyone else, it should still be simple enough to follow that Config-Class and check the Javadoc of those ```@GlobalMapping``` annotations. It's not that we hide anything - it is, as I think, still very much consistent to how we do many other things.

OK, enough the rambling. Too late now anyway. Your turn :wink:

**Comment by sjaakd** [comment]
> OK, enough the rambling. Too late now anyway. Your turn

You don't have to convince me.. Its similar to my case. My case: [gml](http://schemas.opengis.net/gml/3.2.1/feature.xsd). All of our 20 - or so - datatypes that are going to be made the next couple of years are based on gml and related opengis application schemas. They inherit from `AbstractFeatureType` or even more rich `...FeatureTypes` in the opengis inheritance hierarchy. 

Most of the attributes should be populated default or even ignored in the mapping. Building these classes leads to java base classes for which I want to use a common base library (and hence default mappings). 

Note: it should therefor be possible to package MapStruct configuration packages in used libraries. I'm wondering whether we have the same problem there as described in #384 .

**Comment by agudian** [comment]
Gunnar and I talked about this PR on the phone and he wondered why there was this class ```Any``` in ```@GlobalMapping``` is used as default / type wildcard instead of just using ```Object.class```. I didn't remember why I did that and after checking again, there's no techical reason. 

So I've now removed that Any type, rebased, updated the license headers, etc...

**Comment by agudian** [comment]
Closed... replaced by #463

**Pull request closed without merging**
