### PR TITLE
#2303 Generated code should use iteration order preserving LinkedHash(Map|Set) instead of Hash(Map|Set)

### LINKED ISSUE #2303: Retain iteration order for Sorted(Map|Set) values
We experienced a strange bug in our software recently, that took us a while to find. The insight we finally ended up with was:
The iteration order of a specific `Map` value caused the issue. Please consider following example:

```java
class SortedMapDto {
  public SortedMap<String, String> theMap = new TreeMap<>();
}

class TargetDto {
  public Map<String, String> theMap;
}

@Mapper
interface SortedMapMapper {
  TargetDto map(SortedMapDto sortedMapDto);
}
```
The code MapStruct (1.4.1.Final) generates from this is:
```java
// ...
SortedMap<String, String> sortedMap = sortedMapDto.theMap;
if ( sortedMap != null ) {
  targetDto.theMap = new HashMap<String, String>( sortedMap );
}
```

Now as any reasonable Java developer knows, the iteration order of `Map` is not guaranteed. So this bug was of course *our fault* and what MapStruct does is technically correct.

[Immutables](https://immutables.github.io/) though, has a bit more *resilient* take on that by always using `LinkedHashMap` for creating defensive copies of any `Map` types to retain their iteration order.

What I want to suggest is considering to use `LinkedHashMap` (and its counterpart `LinkedHashSet`) just like Immutables for defensive copies instead of `HashMap`.

What's your take on that?

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #2303

### CODE REVIEW

**Review by sjaakd — COMMENTED** [review]
Is it safe to do this? I read on SO that 'LinkedMap' is (after a number of entries) actually faster. But is it always available on lightweight implementations? E.g. Android? I did not check thread safeness yet (I guess it will be the same). 

Anyway.. I'm a bit hesitant if we don't have a (configurable) fallback option. E.g. a `MapperConfig#mapImplementation` or something similar. I would not mind if the default is `LinkedHashSet`.. but just in case.

**Comment by filiphr** [comment]
>Is it safe to do this? I read on SO that 'LinkedMap' is (after a number of entries) actually faster. But is it always available on lightweight implementations? E.g. Android? I did not check thread safeness yet (I guess it will be the same).

I didn't check whether the linked map / set are their on lightweight implementations. However, I would imagine that such a basic map / set should be 😄. Nevertheless, I checked and there is [`LinkedHashMap`](https://developer.android.com/reference/java/util/LinkedHashMap) and [`LinkedHashSet`](https://developer.android.com/reference/java/util/LinkedHashSet) on Android as well.

As for thread safeness, both the linked and non linked variants are the same.

```
Anyway.. I'm a bit hesitant if we don't have a (configurable) fallback option. E.g. a MapperConfig#mapImplementation or something similar. I would not mind if the default is LinkedHashSet.. but just in case.

**Comment by filiphr** [comment]
>Anyway.. I'm a bit hesitant if we don't have a (configurable) fallback option. E.g. a `MapperConfig#mapImplementation` or something similar. I would not mind if the default is `LinkedHashSet`.. but just in case.

I don't like the `MapperConfig` approach. However, people can easily do this with an `@ObjectFactory`.

e.g.

```
public interface MapCreator {

    @ObjectFactory
    static <K, V> Map<K, V> createMap() {
        return new HashMap<>();
    }

    @ObjectFactory
    static <T> Set<T> createSet() {
        return new HashSet<>();
    }
}
```

and then use it in `Mapper#uses` or `MapperConfig#uses`

**Comment by sjaakd** [comment]
> I don't like the `MapperConfig` approach. However, people can easily do this with an `@ObjectFactory`.

Ok. perhaps good to mention that in the release message.

**Review by sjaakd — APPROVED** [review]

**Comment by filiphr** [comment]
Thanks for the review @sjaakd. Will add that to the release notes.

**Pull request merged**
