### PR TITLE
#1940 use annotations as additional criterion to select valuemapping

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by filiphr** [comment]
I don't think that this is needed. You can't really do bean mapping when you do Enum to Enum, String to Enum or Enum to String.

**Comment by sjaakd** [comment]
Unless you map parameters. But having said that.. the target is a bean in that case. So you are probably right

Verstuurd vanaf mijn iPhone

**Comment by filiphr** [comment]
So should we close this and the issue?

**Comment by sjaakd** [comment]
Done

**Pull request closed without merging**
