### PR TITLE
#2795: use 'includeModel' for the 'sourcePresenceCheckerReference' in the 'UpdateWrapper'.

### LINKED ISSUE #2795: Mapstruct 1.5.0 generates invalid code when using @Condition on a presence check for a JsonNullable generic wrapper
- [x] Is this an issue (and hence not a question)? 

Hi,

first, let me say thanks for this awesome project! 👏 

We're currently using Mapstruct 1.5.0RC1 to be able to use the new `@Condition` annotation to map `JsonNullable<T>` generics correctly.

In most of the cases this works perfectly well with the following configuration:

```java
@Mapper(componentModel = "spring")
public abstract class MapperConfig {

    <T> T unwrap(JsonNullable<T> jsonNullable) {
        return jsonNullable.orElse(null);
    }

    <T> JsonNullable<T> wrap(T object) {
        return JsonNullable.of(object);
    }

    @Condition
    <T> boolean isNotEmpty(JsonNullable<T> field) {
        return field != null && field.isPresent();
    }

}
```

However, there's a certain edge case, where mapping fails when a SourceObject contains multiple JsonNullable objects with *different*! inner types:

```java
public class TripDto {

    @JsonProperty("id")
    private long id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("car")
    private JsonNullable<CarDto> car = JsonNullable.undefined();

    @JsonProperty("plane")
    private JsonNullable<PlaneDto> plane = JsonNullable.undefined();

    @JsonProperty("ship")
    private JsonNullable<ShipDto> ship = JsonNullable.undefined();

...
}
```

With the following mapper:

```java
@Mapper(componentModel = "spring", uses = {MapperConfig.class, CarMapper.class, PlaneMapper.class, ShipMapper.class}, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public abstract class TripMapper {

    public abstract TripDto tripToTripDto(Trip trip);

    public abstract Trip tripDtoToTrip(TripDto tripDto);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", ignore = true)
    public abstract Trip updateTripWithTripDto(TripDto update, @MappingTarget Trip destination);

}
```

where `CarMapper` and `PlaneMapper` contain `updateXWithXDto` methods as well (but `ShipMapper` doesn't!) the following invalid uncompilable `TripMapperImpl` is generated:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-03-22T12:29:39+0100",
    comments = "version: 1.5.0.RC1, compiler: javac, environment: Java 17.0.1 (Eclipse Adoptium)"
)
@Component
public class TripMapperImpl extends TripMapper {

    private final MapperConfig mapperConfig;
    private final CarMapper carMapper;
    private final PlaneMapper planeMapper;
    private final ShipMapper shipMapper;

    @Autowired
    public TripMapperImpl(MapperConfig mapperConfig, CarMapper carMapper, PlaneMapper planeMapper, ShipMapper shipMapper) {

        this.mapperConfig = mapperConfig;
        this.carMapper = carMapper;
        this.planeMapper = planeMapper;
        this.shipMapper = shipMapper;
    }

    @Override
    public TripDto tripToTripDto(Trip trip) {
        if ( trip == null ) {
            return null;
        }

        TripDto tripDto = new TripDto();

        tripDto.setId( trip.getId() );
        tripDto.setName( trip.getName() );
        tripDto.setCar( mapperConfig.wrap( carMapper.carToCarDto( trip.getCar() ) ) );
        tripDto.setPlane( mapperConfig.wrap( planeMapper.planeToPlaneDto( trip.getPlane() ) ) );
        tripDto.setShip( mapperConfig.wrap( shipMapper.shipToShipDto( trip.getShip() ) ) );

        return tripDto;
    }

    @Override
    public Trip tripDtoToTrip(TripDto tripDto) {
        if ( tripDto == null ) {
            return null;
        }

        Trip trip = new Trip();

        trip.setId( tripDto.getId() );
        trip.setName( tripDto.getName() );
        if ( org.mapstruct.ap.internal.model.MethodReferencePresenceCheck@431f9bbd ) {
            if ( trip.getCar() == null ) {
                trip.setCar( new Car() );
            }
            carMapper.updateCarWithCarDto( mapperConfig.unwrap( tripDto.getCar() ), trip.getCar() );
        }
        if ( org.mapstruct.ap.internal.model.MethodReferencePresenceCheck@f068cad8 ) {
            if ( trip.getPlane() == null ) {
                trip.setPlane( new Plane() );
            }
            planeMapper.updatePlaneWithPlaneDto( mapperConfig.unwrap( tripDto.getPlane() ), trip.getPlane() );
        }
        if ( mapperConfig.isNotEmpty( tripDto.getShip() ) ) {
            trip.setShip( shipMapper.shipDtoToShip( mapperConfig.unwrap( tripDto.getShip() ) ) );
        }

        return trip;
    }

    @Override
    public Trip updateTripWithTripDto(TripDto update, Trip destination) {
        if ( update == null ) {
            return destination;
        }

        if ( update.getName() != null ) {
            destination.setName( update.getName() );
        }
        if ( org.mapstruct.ap.internal.model.MethodReferencePresenceCheck@ea12f06a ) {
            if ( destination.getCar() == null ) {
                destination.setCar( new Car() );
            }
            carMapper.updateCarWithCarDto( mapperConfig.unwrap( update.getCar() ), destination.getCar() );
        }
        if ( org.mapstruct.ap.internal.model.MethodReferencePresenceCheck@abf369b7 ) {
            if ( destination.getPlane() == null ) {
                destination.setPlane( new Plane() );
            }
            planeMapper.updatePlaneWithPlaneDto( mapperConfig.unwrap( update.getPlane() ), destination.getPlane() );
        }
        if ( mapperConfig.isNotEmpty( update.getShip() ) ) {
            destination.setShip( shipMapper.shipDtoToShip( mapperConfig.unwrap( update.getShip() ) ) );
        }

        return destination;
    }
}
```

Where PresenceChecks `isNotEmpty` for the JsonNullables should be present, a token `org.mapstruct.ap.internal.model.MethodReferencePresenceCheck@xxxx` is generated instead.

Note that this only happens when it's a JsonNullable with our own `isNotEmpty` Condition and when the target Type mapper also implements a `updateXWithXDto` method. That's why `mapperConfig.isNotEmpty( update.getShip() )` is generated correctly.

I have created a Short, Self Contained, Correct Example (SSCCE) at this repository: https://github.com/goldflam-gmbh/mapstruct-presence-check-error

If you check this out and run a `mvn clean compile` you will get the result mentioned partially above.

This may be related to #2377...

Best regards,
Tobias

### PR DESCRIPTION
**Pull request by Zegveld**
fixes #2795

### CODE REVIEW

**Comment by filiphr** [comment]
The fix looks straightforward @Zegveld, I have only one remark. Is it really needed for the test to be so complex? Can't we reach the same problem with a reduced number of classes and configuration?

**Comment by Zegveld** [comment]
> The fix looks straightforward @Zegveld, I have only one remark. Is it really needed for the test to be so complex? Can't we reach the same problem with a reduced number of classes and configuration?

I tried a simplified version, but then it suddenly did not use the `UpdateWrapper` variant anymore.
If you can find a way to get a simpler version with the `UpdateWrapper` variant please do.

**Comment by filiphr** [comment]
@Zegveld I gave it a go. Let me know what you think. If you are OK with it go ahead with the merge once the CI is green

**Comment by Zegveld** [comment]
Looks good, now I also see why I couldn't get a simple reproduction working. I assumed `UpdateWrapper` was used because of an update mapping inside a normal mapper. Never checked if it was also reproducible using an update method itself.
I remember that I noticed the problem inside the normal mapper for the reported situation, therefor tried to reproduce it that way.

**Comment by filiphr** [comment]
Yes the `UpdateWrapper` there is for wrapping updates of nested properties that would be passed to another mapping method

**Pull request merged**
