### PR TITLE
#544 run some checkstyle rules on sources generated by our tests

### PR DESCRIPTION
**Pull request by agudian**
Some tests fail in this PR due to the unused imports... :smile: 

I also fixed two other minor glitches.

### CODE REVIEW

**Comment by sjaakd** [comment]
Failed tests: 
  QualifierTest.shouldMatchClassAndMethod [Expected checkstyle compliant output, but got errors:
/Users/sjaak/Development/java/NetBeansProjects/mapstruct/mapstruct/processor/target/compilation-tests_fork-1_thread-0/generated-sources/mapping/org/mapstruct/ap/test/selection/qualifier/FactMapperImpl.java:3:8: Nicht benutztes import - java.util.ArrayList.
] expected:<[fals]e> but was:<[tru]e>

:smile: ..

**Comment by gunnarmorling** [comment]
> Some tests fail in this PR due to the unused imports...

Cool that we can detect those. Big :+1: for that :)

Do you plan to amend a fix for that issue to this PR as well?

**Comment by sjaakd** [comment]
@gunnarmorling , I'm working on that one :smile:
@agudian, did you know the integrationtest is failing?

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,667,109.597 sec <<< FAILURE! - in org.mapstruct.itest.cdi.CdiBasedMapperTest
org.mapstruct.itest.cdi.CdiBasedMapperTest  Time elapsed: 1,667,109.593 sec  <<< ERROR!
java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.jboss.weld.logging.WeldMessageConveyor

**Comment by sjaakd** [comment]
see #550

**Comment by agudian** [comment]
> java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.jboss.weld.logging.WeldMessageConveyor

Aw, crap... looks like that came from the guava-update (which was required for checkstyle). I can look into it.

Closing this one, as it's being replaced by #550.

**Pull request closed without merging**
