### PR TITLE
#999 make sure that the qualifiedName of the class is trimmed before doing any comparisons for import check

### PR DESCRIPTION
**Pull request by filiphr**
This shouldn't be too complicated 😄

### CODE REVIEW

**Comment by agudian** [comment]
Hehe, nice... 😁 

Could you also add a reproducing test case?

**Comment by agudian** [comment]
And congrats to #1000 👍

**Comment by filiphr** [comment]
>Could you also add a reproducing test case?

Do you mean I should make the `isImported` of the `TypeFactory` just for the test? Or you mean something else? Currently, we don't have tests which test the generated code (or do we?)

>And congrats to #1000 👍

Thanks 😄

**Comment by agudian** [comment]
Sure we do :)

Check the usages of `org.mapstruct.ap.testutil.runner.GeneratedSource`

**Comment by filiphr** [comment]
My bad I didn't know that. Thanks for pointing it out.

I added the test case 😄

**Comment by filiphr** [comment]
I forgot to add `@IssueKey`. I'll add it now

**Comment by agudian** [comment]
Alright, looks good! Squash and merge, please :)

**Comment by sjaakd** [comment]
> Alright, looks good! Squash and merge, please :)

Nothing more to add. 👍

**Comment by filiphr** [comment]
Thanks for the review. I am waiting for the build, once that one is done then I'll squash and merge 😄

**Comment by agudian** [comment]
Mine's already building, I'll push right after it's finished... shouldn't have any conflicts with you, though.

**Comment by sjaakd** [comment]
jenkins, please test this.

**Comment by filiphr** [comment]
ok to test

**Comment by sjaakd** [comment]
test this please

**Pull request merged**
