### PR TITLE
Travis CI to check pull requests

### PR DESCRIPTION
**Pull request by velo**
Not sure if this is something you guys wanna see in place, but I enabled travisCI on my fork
https://travis-ci.org/velo/mapstruct

In case you guys wanna this.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, thanks for that suggestion! Atm. we have a Jenkins instance running at https://mapstruct.ci.cloudbees.com/, and so far we are quite happy with it. No need to change that really from my side so far, not sure what you guys think, @sjaakd, @agudian!

**Comment by velo** [comment]
I'm only suggesting it, cause right now, I see there is no CI status on the pull requests....  so I though there was no CI running.

**Comment by agudian** [comment]
I'm happy with cloudbees as well. Some weeks ago, I started on configuring a pull-request builder, but ran into some trouble with missing permissions. I'd like to take that up again, though.

**Comment by velo** [comment]
Well, in any case, this is ready to go...

**Comment by sjaakd** [comment]
> No need to change that really from my side so far, not sure what you guys think,

I'm ok with Couldbees.

**Comment by velo** [comment]
Me too, as I said, I would did this cause there is no pull request checking and I'm looking into doing #610

**Comment by gunnarmorling** [comment]
Hey @velo, good point about the PR builder.

A while ago we checked what possibilities there are with CloudBees and we didn't find a way to work with whitelisting (as I consider building *any* PRs as a security issue, so I'd like to be able to build PRs from new contributors only after one-time approval of a committer).

There is a Jenkins plug-in which allows that, but back then it was'nt available on CloudBees. This supposedly has changed and we are planning to look into enabling it. Should that still not work, I guess using Travis would be a good alternative.

**Comment by agudian** [comment]
@velo thanks again for your PR, I'm gonna close this one, as we got the Jenkins-Integration working by now... :+1:

**Comment by gunnarmorling** [comment]
Cool, thanks a lot @velo for triggering us to look again into the matter and thanks to @agudian for making it happen :)

**Pull request closed without merging**
