### PR TITLE
#892 If multiple setters exist, don't override the setter if it doesn't match the property getters type

### PR DESCRIPTION
**Pull request by agudian**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@agudian So what is the strategy for handling this sort of conflict; if there is any target property with an assignment-compatible type, take that one? What happens in these cases:

* There are multiple assignment compatible candidates, e.g. `setFoo(int)` and `setFoo(long)`. Would it be ensured that the former would be used for mapping an `int` property? I reckon that yes because it would take the first assignment-compatible one and the call would be generated; the correct one will be linked by the compiler as per the Java method resolution rules.
* There are multiple non compatible candidates, `setFoo(String)` and `setFoo(BigInteger)`. I don't think we can choose one reasonably, rather an ambiguity error should be raised (though we don't provide a way to resolve the case currently). That would have to be fixed, too (could be done separately, e.g. by adding `@PropertyMapping#resultType()`. For now I'd be fine with an error clearly indicating the situation (it's really a special case).

**Comment by agudian** [comment]
I think the "right" solution would be to promote all possible variants and let the method selection mechanism do its magic. That would cover the points you mentioned and allow for some error messages. But that would require some refactoring and it would make several methods more complicated.
As we're dealing with a strange edge case here, I went for a simple approach that only prevents returning a "worse" setter if there was one found previously already.

* If there is only one setter for the property name, it will be returned regardless of its argument type (as it has been before). 
* If there is more than one setter and there is a getter available to determine the type, the last setter with an assignment compatible argument type is returned. 
* If there is more than one setter and no getter is available, nothing changes compared to how it was before: the last setter is returned.

So it's not as smart as it could be, but it should suffice to prevent choosing the wrong setter... 😬

**Comment by gunnarmorling** [comment]
I'm not sure I agree on automatically selecting a target setter if there are several ones which all need conversion. I don't think we can make any reasonable decision in this case. But we can leave that for another time, the change at hand already is an improvement.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thx, @agudian!

**Pull request closed without merging**
