### PR TITLE
Add locale to test

### PR DESCRIPTION
**Pull request by incaseoftrouble**
Followup to #2568

### CODE REVIEW

**Comment by incaseoftrouble** [comment]
@filiphr I think this error is beyond my control. Probably simply re-running the test should fix the issue:
```
Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc (output-html) on project mapstruct-documentation: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc failed: Plugin org.asciidoctor:asciidoctor-maven-plugin:2.1.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.jruby:jruby-complete:jar:9.2.17.0, org.asciidoctor:asciidoctorj:jar:2.5.1, org.asciidoctor:asciidoctorj-api:jar:2.5.1, com.beust:jcommander:jar:1.72: Could not transfer artifact org.jruby:jruby-complete:jar:9.2.17.0 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/9.2.17.0/jruby-complete-9.2.17.0.jar: Connection reset -> [Help 1]
```

**Comment by filiphr** [comment]
Thanks a lot for this @incaseoftrouble. Yes I know that the error is not your fault, that one is a bit flaky 😄

**Comment by gunnarmorling** [comment]
Hey @filiphr, re that failure, we used to have those in Debezium's CI too,
but we got rid of them with some Maven timeout settings, e.g. here:
https://github.com/debezium/debezium/blob/master/.github/workflows/mysql-workflow.yml#L58
(just in case you don't do the same yet for MapStruct).

>

**Comment by filiphr** [comment]
Thanks @gunnarmorling, I've tried the same in https://github.com/mapstruct/mapstruct/blob/master/.github/workflows/main.yml#L8, but I think that they are not properly picked up on Windows, I think that using `${MAVEN_ARGS}` is not how you pass arguments for windows 😄 . In any case, I had a small hope that Maven 3.8.2 will fix this problem (they had something in the release notes), but it seems that's not the case

**Pull request merged**
