### PR TITLE
#1032 Update license headers to 2017

### PR DESCRIPTION
**Pull request by agudian**

### CODE REVIEW

**Comment by filiphr** [comment]
Do we also need to update the [LICENSE.txt](https://github.com/mapstruct/mapstruct/blob/master/LICENSE.txt) as well?

**Comment by agudian** [comment]
> Do we also need to update the LICENSE.txt as well?

Right. I'll update it and commit it directly, then merge it to master.

**Comment by gunnarmorling** [comment]
Already did it for 1.1.

**Comment by gunnarmorling** [comment]
Ok, so I'll leave the merge to master to you, @agudian. Thx!

**Comment by agudian** [comment]
there's also one missing in the root pom.xml 🙄

**Pull request merged**
