### PR TITLE
#544 run some checkstyle rules on sources generated by our tests and fix failing testcases

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by sjaakd** [comment]
@agudian, somehow also got some German error lines: 'Nicht benutztes import' .. its a minor thingy...

**Comment by agudian** [comment]
> @agudian, somehow also got some German error lines: 'Nicht benutztes import' .. its a minor thingy...

I already wondered how that came into the output you posted...

**Comment by agudian** [comment]
@sjaakd, I've created a PR on your branch to fix the guava version conflict between checkstyle and CDI.

**Comment by sjaakd** [comment]
@agudian , I'm ok with your work. Did you checkout my fixes? Can I merge?

**Comment by agudian** [comment]
Looks good to me. Please go ahead :+1:

**Comment by sjaakd** [comment]
@agudian .. thanks!.

**Pull request merged**
