### PR TITLE
#991 Split reference guide source into an adoc file per chapter

### PR DESCRIPTION
**Pull request by Captain1653**

### CODE REVIEW

**Comment by Captain1653** [comment]
> @Captain1653 : did you try to generate the PDF / HTML? Is there a diff? Might be worthwhile to compare the results of old-and-new on PDF .. I think its even possible in acrobat reader.

I have compared it manually, but you are right. I'll attach comparasion's report

**Comment by sjaakd** [comment]
> I have compared it manually, but you are right. I'll attach comparasion's report

Adding a report  is not really necessary.. If you verified it, I believe you :smile:

**Comment by Captain1653** [comment]
Unfortunately, I don't believe myself ).
So, I have verified it with services: [textcompare](https://www.textcompare.org/pdf/)  and  [diffchecker](https://www.diffchecker.com/diff). 

I also attach two files. Maybe somebody know some good tool or service for verify.

[original.pdf](https://github.com/mapstruct/mapstruct/files/3542526/original.pdf)
[refactor-guide.pdf](https://github.com/mapstruct/mapstruct/files/3542527/refactor-guide.pdf)

**Comment by sjaakd** [comment]
I tried this one: https://draftable.com/compare/tEHXpvwhylSi

Seems they are identical .. Please go ahead and merge.

**Pull request merged**
