### PR TITLE
#689, add built in methods to/from xmlGregorianCalendar and Joda Types.

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by sjaakd** [comment]
I'm doubting whether to put commit: 	185b9c7 in. Determining conversion from `LocalDateTime`, `LocalDate` en `LocalTime` should perhaps be a user choice.

I'm also doubting whether to set the timezone field in xmlGregorianCalendar to UNDEFINED for the local Joda types or to the default. You can make argument for both cases.

**Comment by sjaakd** [comment]
As an additional thought, we should perhaps disallow 2 step mappings:
* 2x builtin
* conversion / builtin
* 2x conversion

With 'simple' intermediate types, such as `String` and `Date`.. I

**Comment by agudian** [comment]
Hmm, something in the tests is still dependent on the locale of the build system.

**Comment by agudian** [comment]
> As an additional thought, we should perhaps disallow or deprioritize 2 step mappings ...

:+1: - this tends to create some funny conversions (and as some user reports suggest, that might not always be stable, but can depend the specific beans a single mapper deals with). Not sure though, if we should completely disable it, or just make it the "last resort" (but with deterministic behaviour for each specific pair of types).

**Comment by sjaakd** [comment]
> or just make it the "last resort" (but with deterministic behaviour for each specific pair of types).

That was exactly my thinking. I think we now break our search on the first match in a 2 step mapping. What if we don't do that and add a `Selector` that sorts on the -in-between-type-? So last prio:
* String
then
*Date
etc..

**Comment by agudian** [comment]
Sounds good.

Wdyt, should this PR be part of the CR1 release? And the change to the selector as well?

**Comment by sjaakd** [comment]
> Wdyt, should this PR be part of the CR1 release? And the change to the selector as well?

I think this is a separate issue (I'll write one). Lets keep this one centered around Joda, WDYT?

**Comment by agudian** [comment]
Anything left to be done here?

**Comment by sjaakd** [comment]
> Anything left to be done here?

In principle not.. I'm just doubting about commit 185b9c7.. WDYT? Shall I leave it out or in?

**Comment by agudian** [comment]
When in doubt, then leave it out. It's an old saying, right? :wink:

I guess we can still discuss that in our next hangout with Gunnar in time for the Final.

**Comment by sjaakd** [comment]
Ok.. so we reschedule this one for the final, right? Tomorrow CR1?

**Comment by agudian** [comment]
Yes, let's wait with this another week and do the release tomorrow.

**Comment by gunnarmorling** [comment]
@sjaakd @agudian Where are we with this one? Is it good to go?

**Comment by sjaakd** [comment]
same doubt as in #893

**Comment by gunnarmorling** [comment]
Hi @sjaakd, regarding

> In principle not.. I'm just doubting about commit 185b9c7.. WDYT? Shall I leave it out or in?

If in doubt leave it out? I'm not too keen on adding more stuff for Joda anyways (as it's been replaced with Java 8's API), so if we aren't sure let's not add this one. Could you update the PR?

**Comment by sjaakd** [comment]
@gunnarmorling .. I leave it out and merge then?

**Comment by sjaakd** [comment]
Done!

**Comment by sjaakd** [comment]
@gunnarmorling : do you still want to review the remainder?

**Comment by gunnarmorling** [comment]
Go for it if you think it's good. Otherwise I'll take a look tomorrow.

**Comment by gunnarmorling** [comment]
+1. Could you also add a mention of the new conversions in the docs? Thanks!

**Pull request merged**
