### PR TITLE
#3089 Improve support for Map attributes for immutables

### PR DESCRIPTION
**Pull request by thunderhook**
Work was already done by @GVladi, thank you very much. I just cleaned up the generated class to be checkstyle-conform.

@filiphr is it possible to change the commit author? Would be nice, because I don't want to take credit for someone else's work.

### CODE REVIEW

**Review by filiphr — CHANGES_REQUESTED** [review]
>@filiphr is it possible to change the commit author? Would be nice, because I don't want to take credit for someone else's work.

Yes I can do that. Is there a commit by @GVladi that I can look into in order to be able to get the email (event if it is the noreply github one)? I would also need the consent from @GVladi that is is OK to put him as an author.

@thunderhook I see that @GVladi shared a patch in the issue, which I missed. I would prefer if we add a dedicated test for this in the `_3089` package. Can you perhaps do that @thunderhook? I will add both you and @GVladi as authors in that case, @GVladi as the main one.

**Comment by GVladi** [comment]
@filiphr I don't mind, if you put me on the authors list ;-)

**Comment by thunderhook** [comment]
Of course. I have provided a separate test. Just tell me if there is something else you want me to change.

**Comment by filiphr** [comment]
Thanks @GVladi and @thunderhook. I've merged this manually in f61a3acec301de2a781bd46a56cdcf5c83ca159e

**Pull request closed without merging**
