### PR TITLE
#2195 @Beanmapping#resultType should be used to construct return type also if it's a builder

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by sjaakd** [comment]
@filiphr I'm a but struggling with the reproducer A. Do we / or did we support a case were mapping methods return a builder?

The point is: the builder itself requires (sometimes) a factory method. For the target type, we analyse the builder type to check the creation method. But if we're analysing at the builder itself (as return type), we are not going to look for the a creation method in the target type. The issue #2195 seems to suggest something like that.

 It kind of makes sense (since we accept builders also as target type and we have methods that take a target and return type. I need to analyse that case, to see how that works and whether we can reuse that solution. 

What's your opinion here?

**Comment by filiphr** [comment]
>Do we / or did we support a case were mapping methods return a builder?

Mapping method returning a builder is nothing more than mapping into some kind of arbitrary type. We supported that (with builder with `setX`) even before we had the builder support.

I am not quite sure that I follow the problem in #2195. I think I saw one place where the method return type differed than the BeanMapping result type, i.e. the BeanMapping result type was the builder. In my opinion that should be a compile error. 

The regression comes from https://github.com/mapstruct/mapstruct/commit/33710584d33856495992c7cab511b4a16643f53e, right? In my opinion we should get the result type that should be mapped (either via BeanMapping or the method) and then go and look for a builder. Right now we have the `returnTypeBuilder` in the `BeanMappingMethod`, but that can be the incorrect builder.

Not sure if it makes sense what I am saying.

**Comment by sjaakd** [comment]
> Mapping method returning a builder is nothing more than mapping into some kind of arbitrary type. We supported that (with builder with `setX`) even before we had the builder support.

True.. But we only look for factory methods in used mappers and the mapper itself. If you return a builder with a private constructor and a create method, we should use the create mapping and that's something we don't do for normal types.

**Comment by filiphr** [comment]
We don't look for factory methods in any type. We only do a special sequence to determine if a certain type has a builder. And for that we need the builder to have a factory in the type it is building.

**Review by filiphr — APPROVED** [review]
LGTM

**Comment by sjaakd** [comment]
@filiphr thanks for the review

**Pull request merged**
