### PR TITLE
#2215: Avoid NPE in IntelliJ EAP 2020.3

### LINKED ISSUE #2215: NPE when running MapStruct from IntelliJ 2020.3EAP
- [x] Is this an issue (and hence not a question)? 

I recently upgraded to IntelliJ 2020.3 EAP and the MapStruct annotation processor throws a NPE when compiling a `@Mapper` class. 

```
C:\Users\bj\IdeaProjects\untitled2\src\main\java\PersistenceMapper.java:5:17
java: Internal error in the mapping processor: java.lang.NullPointerException  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.createManifestUrl(DefaultVersionInformation.java:182)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.openManifest(DefaultVersionInformation.java:153)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.getLibraryName(DefaultVersionInformation.java:129)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.getCompiler(DefaultVersionInformation.java:122)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.fromProcessingEnvironment(DefaultVersionInformation.java:95)  
	at org.mapstruct.ap.internal.processor.DefaultModelElementProcessorContext.<init>(DefaultModelElementProcessorContext.java:54)  
	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:264)  
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)  
	at org.jetbrains.jps.javac.APIWrappers$ProcessorWrapper.process(APIWrappers.java:59)  
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)  
	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:162)  
	at com.sun.proxy.$Proxy18.process(Unknown Source)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)  
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)  
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)  
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:219)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:496)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:348)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:272)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:226)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1436)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1100)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1219)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:832)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:419)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)  
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)  
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)  
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)  
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)  
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)  
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)  
	at java.base/java.lang.Thread.run(Thread.java:834)  
```

When I debug the compilation process, I can see that it's caused by the `ProcessingEnvironment` instance which is now a `Proxy` in `org.mapstruct.ap.internal.processor.DefaultVersionInformation#getCompiler(javax.annotation.processing.ProcessingEnvironment)`.

In 2020.2, `processingEnv.getClass().getName()` returns `com.sun.tools.javac.processing.JavacProcessingEnvironment`.
In 2020.3, `processingEnv.getClass().getName()` returns `com.sun.proxy.$Proxy19`, and later on `clazz.getClassLoader().getResource(classFileName)` returns `null`.

**Steps to reproduce**
* open the attached project in IDEA 2020.3 EAP
* compile `PersistenceMapper.java`

**Steps to debug**
* The project should be pre-configured to launch the compilation process with a debugger listening on port 5050
* Run the debug configuration to attach the IDE to the compilation process
* Put a breakpoint in `org.mapstruct.ap.internal.processor.DefaultVersionInformation#getCompiler(javax.annotation.processing.ProcessingEnvironment)`
* Recompile `PersistenceMapper.java` using F9

**Additional info**
> IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.4203.26, built on September 30, 2020
IntelliJ IDEA EAP User
Expiration date: October 30, 2020
Runtime version: 11.0.8+10-b1098.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: PlantUML integration, Lombook Plugin, YourKit Java Profiler 2019.8-b137 Integration, org.sonarlint.idea, MavenRunHelper, com.dmarcotte.handlebars

MapStruct version 1.4.0.Final

### PR DESCRIPTION
**Pull request by filiphr**
Starting from IntelliJ 2020.3 (Build 203.4203.26) the ProcessingEnvironment is wrapped in a Proxy class by IntelliJ.
MapStruct should gracefully handle that and not throw an NPE.
Additionally, we should do best effort to put the used compiler in the generated annotation info

Fixes #2215

### CODE REVIEW

**Review by sjaakd — APPROVED** [review]
LGTM

**Comment by filiphr** [comment]
Thanks for the review @sjaakd

**Comment by shiv-asati** [comment]
How to resolve this issue can anyone help me

**Comment by filiphr** [comment]
@shiv-asati you need to update MapStruct to at least 1.4.1.Final.

**Pull request merged**
