### PR TITLE
Fixes issue #1273 using NVMS#RETURN_DEFAULT when using collections

### PR DESCRIPTION
**Pull request by kevcodez**
Fix for NullValueMappingStrategy#RETURN_DEFAULT when using collections.

This is a proposed fix for https://github.com/mapstruct/mapstruct/issues/1273.

When mapping a collection using NullValueMappingStrategy#RETURN_DEFAULT and the source is null, the target will be an empty collection.

### CODE REVIEW

**Comment by kevcodez** [comment]
@filiphr Could you please review? This might be relevant for 1.2.0.Final I suppose

**Comment by filiphr** [comment]
@kevcodez I didn't see your message until now :). In any case, I have already reviewed it, have a look at my review.

**Comment by kevcodez** [comment]
@filiphr Would you add the IterableCreation to the appropriate Wrapperclasses (Java)? I started doing that, but this causes package cycles, thus I placed it in the PropertyMapping.

**Comment by filiphr** [comment]
@kevcodez you don't need the `IterableCreation`. That one is mostly used for the size and we don't need that here. I mentioned it only because in there one can see how to do the implementation type.

I would just pass a boolean that will be `mapNullToDefault` or something like that (we have that in the `MappingMethod`s).

If that boolean is `true` I would call the macro `initTargetObject` from the `CommonMacros.ftl`, otherwise just return `null`.

**Comment by filiphr** [comment]
@kevcodez we are going to include this PR in the 1.2.0.Final release 😄. When will you have time to go over my comments?

**Comment by kevcodez** [comment]
@filiphr hopefully tomorrow. If you get no reply til monday, I wont be able to make it

**Comment by kevcodez** [comment]
@filiphr I implemented your feedback, can you have another look?

**Comment by filiphr** [comment]
@kevcodez thanks, I noticed the typo later. I have pushed an update. Also don't worry I am going to squash everything in once commit and you are going to be the author of everything 😄

**Comment by kevcodez** [comment]
@filiphr Sure, it is fine. I used the eclipse formatter XML from MapStruct in IntelliJ. Good to know :)

**Comment by filiphr** [comment]
We actually have an IntelliJ formatter in git [here](https://github.com/mapstruct/mapstruct/blob/master/etc/mapstruct.xml), which is actually up to date. We need to make sure that we document this better 😄

**Comment by filiphr** [comment]
@kevcodez I have merged this into master. Thanks a lot for the PR :). I've also added you to our copyright https://github.com/mapstruct/mapstruct/commit/98bdc3612f5beb6d89596a280e5974cd2dce282b

**Pull request merged**
