### PR TITLE
#449 Handle XmlGregoriancalendar from String with empty date format as x...

### PR DESCRIPTION
**Pull request by sjaakd**
...ml datatype

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Ok, I understood it wrong a bit yesterday. I thought `XmlGregorianCalendar` would have its own means for parsing strings with another format specification.

But actually one cannot specify a format here, Strings directly parsed into `XmlGregorianCalendar` always need to adhere to the XML lexical representation. So `Mapping#dateFormat()` and friends still would always expect a formatting string understood by `DateFormat`.

**Comment by sjaakd** [comment]
> But actually one cannot specify a format here, Strings directly parsed into XmlGregorianCalendar always need to adhere to the XML lexical representation

Exactly. You could say that our initial implementation missed the primary use case of `XmlGregorianCalendar`

> So Mapping#dateFormat() and friends still would always expect a formatting string understood by DateFormat.

Yep.. That still remains as is.

--------
It is however a break with the current implementation behavior and deviates from the other `Date` related formats. So I guess we need to spent some words on it in the documentation.

**Comment by sjaakd** [comment]
Proposal for text in documentation, additional bullet to end of chapter 5.1:

"* When converting from a `java.lang.String`, omitting `Mapping#dateFormat` results in using the default pattern and date format symbols for the default locale. An exception to this rule is `XmlGregorianCalendar` which results in parsing the `String` according to [XML Schema 1.0 Part 2, Section 3.2.[7-14].1, Lexical Representation](http://www.w3.org/TR/xmlschema-2/#dateTime-order)."

**Comment by agudian** [comment]
> "* When converting from a java.lang.String, omitting Mapping#dateFormat results in using the default pattern and date format symbols for the default locale. An exception to this rule is XmlGregorianCalendar which results in parsing the String according to XML Schema 1.0 Part 2, Section 3.2.[7-14].1, Lexical Representation."

How about using just "String" iso "java.lang.String" (I think the chances are low that someone reads this to be the other string from package ```underwear``` :wink:). 

For the second sentence, I'd make it more plain to read: "An exception to this rule is XmlGregorianCalendar which cannot be configured with a date format, as the String value always needs to be in the format according to XML Schema 1.0 Part 2, Section 3.2.[7-14].1, Lexical Representation." -- unless I missunderstood the issue...

**Comment by sjaakd** [comment]
It still can be configured with a date format . It then works similar as the String to date formats,

**Comment by gunnarmorling** [comment]
> How about using just "String" iso "java.lang.String"

+1. Sounds good otherwise.

**Comment by gunnarmorling** [comment]
Thanks, @sjaakd!

**Pull request merged**
