### PR TITLE
#407 Fix primitive handling for nested properties

### PR DESCRIPTION
**Pull request by shasait**

### CODE REVIEW

**Comment by agudian** [comment]
Your commit contains changes from #400 which are not really necessary for fixing this issue, right? Could you drop them out?

And using or extending a Unit-Test from within the processor module would be favourable. The integration tests are more bulky and harder to execute from within the IDE (you always need to mvn install on the command line first, etc) - so when ever possible, we try to create reproducer tests and tests for new features as Unit-Tests.

But I like the idea how you solved the Problem itself! :+1:

**Comment by shasait** [comment]
Hmmm - wanted to squash both commits into one so the PR stays small - but it doesn't look correct

**Comment by shasait** [comment]
ahh - because I reverted 400 it now looks this way... should be correct then.

**Comment by shasait** [comment]
Yes - I saw this in the documentation, but my problem was, that EGit on squash opens a dialog were lines starting with "#" are comments therefore I was littlebit lost - but next time I know better and will simple change the message afterwards...

**Pull request merged**
