### PR TITLE
#1198: Support @Named variables to address mapper inheritance when su…

### PR DESCRIPTION
**Pull request by jmuis**
Just noticed imports ordering has changed, but please have a look at the general idea, more than happy to clean it up, add documentation, etc. if suggestion / improvement will be accepted at all.

### CODE REVIEW

**Comment by filiphr** [comment]
@jmuis thanks for the PR. I think that the idea is really good. Especially to support cross jar compilations.

The implementation looks really simple :). Apart from adding documentation and tests. I think we'll need an integration test with multiple modules for this to be tested as well.

I also think that we need to use a different Annotation. I don't think that the `@Named` is correct here. Maybe something like `@Param`.  @gunnarmorling, @agudian, @sjaakd what do you think?

**Comment by jmuis** [comment]
Hi, 

Thanks for your quick & positive feedback. 
We had some discussion around @Named as well, but actually it does make sense IMHO, as you are naming a parameter. Obviously a new annotation is possible as well, technically I have nothing against it. It might just be a little confusing if you already have something around which is called @Named.
 
How would you do unit testing? Create a 'dummy' project just containing base mappers?

**Comment by filiphr** [comment]
@jmuis let's see what the others say about the annotation. I think that it will confuse user, especially if you look at the Javadoc of `@Named`, it is meant to be used as a `@Qualifier`, it is even annotated with that. It is a way to give a name to a method that can be then used in `@Mapping#qualifiedByName()` and the other variants. That is the only reason why I think that it might confuse users to use that.

As for the unit testing, you don't have to create a "dummy" project. We have our own runner `AnnotationProcessorTestRunner` that invokes the javac compiler and the eclipse compiler during tests. just have a look at any test to see how it works. Apart from the test, you will need to create classes and mapper that will map them. 

Apart from the "unit" test. I will suggest to create an integration test as well. For that you can have a look at the tests in the `integrationtest` module. Those are a bit more complex 😄. You will need to create a test and use the `ProcessorSuiteRunner` to say where the folder is. For this you will need to create a "dummy" maven project. Have a look at the `NamingStrategyTest`. I would suggest running that test from a command line via maven 😄.

If something is not clear, just let me know and I can help you out.

**Comment by agudian** [comment]
Hmm, doesn't this work with JDK 8 out of the box? Or do you need to pass an additional compiler arg when compiling? Ah, found it: http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#options (it speaks about making the parameter name available for reflection, but I would guess that it could do the trick for us as well)... Did you try that?

**Comment by agudian** [comment]
> Hmm, doesn't this work with JDK 8 out of the box?...... Did you try that?

Sorry, you wrote that in the issue already.

**Comment by gunnarmorling** [comment]
Not going to merge this as discussed on the issue itself. I think Java 8 parameter names should be the way to go and we shouldn't provide an alternative to that standard mechanism.

**Pull request closed without merging**
