### PR TITLE
#1231 Add japicmp for the MapStruct API

### LINKED ISSUE #1231: Set up japicmp on the API module to track API changes
See https://github.com/siom79/japicmp

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #1231

We could also add the generated HTML to some section on our website

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM. I'm not sure about publishing the report as is, as it's often quite confusing when seeing it for the first time. I'd prefer to use it as input for ourselves, e.g. for writing the change notes.

**Comment by filiphr** [comment]
I agree with you, the report is quite exhaustive and I am not sure if it will be clear to everyone. Using it for us is not bad.

I'll merge this once all the checks pass 😄

**Comment by filiphr** [comment]
Thanks for reviewing this @gunnarmorling. The closing earlier was a mistake 😄

**Comment by gunnarmorling** [comment]
Cool, thanks, @filiphr!

**Pull request merged**
