### PR TITLE
#710 Play nice with other processors for generating supertypes of mapping source/target types

### PR DESCRIPTION
**Pull request by gunnarmorling**
Hey @agudian, @sjaakd Got something for 1.0.1 :)

This re-arranges a bit the pieces in `MappingProcessor`:

* First process any mappers deferred from previous rounds
* Then process mappers from this round

If in einer step a source/target type with an incomplete hierarchy is encountered, its processing is deferred to a next round.

We might defer handling in some other cases as well (e.g. a superclass for a mapper or config type could be generated?!), but as this seems very exotic, I'd say let's wait for the actual need. Should be simple to do with the general deferring mechanism in place.

Note that this does not address the Lombok issue, but it improves the situation when using MapStruct with other processors playing by the rules of JSR 269.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Oops, just seeing I accidentally merged this already :/ I think it's good, but please let me know if you have any remarks.

**Comment by agudian** [comment]
One thing that jumps to my attention is the tab-indentation in the integration test java files... :eyes: 

But on the stuff itself: did you test-drive it in Eclipse as well? 

And how about the idea with collecting and passing all the originatingElements during the mapper creation? That sounded like it could also help us getting things right(er).

**Comment by agudian** [comment]
And one more thing. How about remembering only the classnames in `deferredMappers`, to avoid keeping references to the `TypeElement` instances. And when using the set later on, you do a fresh lookup of the new `TypeElement` using the class name anyway.

**Comment by gunnarmorling** [comment]
> One thing that jumps to my attention is the tab-indentation in the integration test java files...

Agh... I suppose CS doesn't check these?

> But on the stuff itself: did you test-drive it in Eclipse as well? 

Hum, no, but good idea. I'll give it a try

> And how about the idea with collecting and passing all the originatingElements during the mapper creation?

Right, working on this as we speak as part of #709.

> How about remembering only the classnames in deferredMappers

Ah yes, should have done that to begin with. Thanks!

I'll send a PR with the adjustments.

**Pull request merged**
