### PR TITLE
#456 Avoiding to print multiple consecutive blank lines

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by agudian** [comment]
The output looks very good on Windows, even the linebreaks are correct now... :+1: 

Do you rebase and merge yourself?

**Comment by gunnarmorling** [comment]
> The output looks very good on Windows, even the linebreaks are correct now... :+1:

Cool, glad to hear. Yes, it bugged me that we'd always use the line breaks from the templates rather than from the current system :)

Ah, to be sure, could you take the JAR built on CI (once it's merged) and test that one as well? The templates there should be Linux-style, which should be translated to Windows now properly. Thx!

> Do you rebase and merge yourself?

Just done. Thx!

**Comment by agudian** [comment]
> Ah, to be sure, could you take the JAR built on CI (once it's merged) and test that one as well? The templates there should be Linux-style, which should be translated to Windows now properly. Thx!

Locally, the templates are also with linux line endings, also after the build. The generated sources then all use windows line endings. So it works as you expected it to... :+1:

**Comment by gunnarmorling** [comment]
Cool, thanks for trying! I'm quite happy now with the formatter class; The
onEntry()/onExit() hooks make it much easier to put new logic into the
right place.

**Pull request closed without merging**
