### PR TITLE
#729 Fix trying to resolving constructor on primitive types

### PR DESCRIPTION
**Pull request by greuelpirat**
I have prepared a fix for the NullPointerException. The fix itself was not that hard. But for an dedicated unit test I need some help. The test-framework is quite complicated.

### CODE REVIEW

**Comment by agudian** [comment]
(Message from the pull-request-builder): Admins, please verify this patch for it to build in the pull-request-builder.

**Comment by gunnarmorling** [comment]
@greuelpirat, thanks for looking into this!

Regarding a test, check out `org.mapstruct.ap.test.collection.erroneous.ErroneousCollectionMappingTest`, I think that's where it should go. Actually, `shouldFailToGenerateImplementationBetweenCollectionAndNonCollection()` seems to cover that case on first sight, but apparently something still is different.

In general, we have a custom JUnit runner, `AnnotationProcessorTestRunner` which takes a set of test sources (mappers, source/target beans etc.) and compiles them. Then one can either invoke the generated mapper and test its functionality by asserting the target object of the mapping (e.g. see `CollectionMappingTest`). Or one can assert the presence of specific compilation errors in order to make sure that MapStruct rightfully rejects specific wrong mappings. That's what you see in `ErroneousCollectionMappingTest`.

**Comment by greuelpirat** [comment]
Thank for you help. I have added an unittest. Please check it out.

**Comment by gunnarmorling** [comment]
Merged; Thanks, @greuelpirat!

**Pull request merged**
