### PR TITLE
#291 add test to verify that the simple case (target type with type argu...

### PR DESCRIPTION
**Pull request by agudian**
...ments) already works, clean-up unnecessary "raw" definitions in templates

### CODE REVIEW

**Comment by sjaakd** [comment]
@agudian, tried some command-line git magic to see if I was able to rebase your code. I think (hope :smile: ) I got the hang of it. You should still be the author and its a ffw. merge

**Comment by sjaakd** [comment]
For some reason, this PR does not show as merged.. So'll you have to close I'll have to close it manually

**Comment by agudian** [comment]
Great, thanks, Sjaak!

**Comment by gunnarmorling** [comment]
> For some reason, this PR does not show as merged

Yes, that's normal if you do a rebase of the commits. Technically, the rebase creates new commits (with different SHAs) which are equivalent to the original ones. Thus GitHub doesn't know that you have merged these other commits and you need to close the PR manually.

Thanks btw. for handling this!

**Pull request closed without merging**
