### PR TITLE
#460 add workaround for TypeElements that occasionally seem "empty" during incremental compilation in Eclipse JDT

### PR DESCRIPTION
**Pull request by agudian**
... no tests included... but I tried it with my biggy workspace here... ;)

### CODE REVIEW

**Comment by agudian** [comment]
@sjaakd / @gunnarmorling: do you guys have any opinion on this one? In case you wonder: testing this automatically is next to impossible, and recreating the issue in Eclipse requires a bit of luck as well...

**Comment by gunnarmorling** [comment]
@agudian I think the change itself is good, I got a question on the general desing of `SpecificCompilerWorkarounds`, though.

Shouldn't this be an interface, with different implementations (one for javac, one for Eclipse) and we use the right one depending on the environment? That way e.g. your fix would only be part of the Eclipse impl, whereas the javac-based impl would be a no-op. Would that make sense?

**Comment by agudian** [comment]
> Shouldn't this be an interface, with different implementations (one for javac, one for Eclipse) and we use the right one depending on the environment? That way e.g. your fix would only be part of the Eclipse impl, whereas the javac-based impl would be a no-op. Would that make sense?

Yes, that would make sense. Up until now we created workarounds that worked for both, javac and Eclipse. To make your suggestion work, we'd need to make sure that our detection mechanism for Eclipse / Javac is rock-solid, though... I wouldn't trust the current implementation in ```DefaultVersionInformation``` that far... :wink: - The ramifications of a false-negative detection of the eclipse compiler are pretty severe, in that the processor would not work properly. That's something I wouldn't try to squeeze in for Beta4.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thx, @agudian!

**Comment by gunnarmorling** [comment]
Created #484 for making this an interface as discussed above.

**Pull request closed without merging**
