### PR TITLE
#213 Updating license header

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@sjaakd I noticed `ChartPositions` and one other file had a slightly different license header than the other files (not sure why the license plug-in did not detect it?). I've changed it to the standard header, hoping that's alright with you.

**Comment by sjaakd** [comment]
> @sjaakd I noticed ChartPositions and one other file had a slightly different license header than the other files (not sure why the license plug-in did not detect it?). I've changed it to the standard header, hoping that's alright with you.

No problem whatsoever. :smile: must have been accidental..

**Comment by agudian** [comment]
> not sure why the license plug-in did not detect it?

My guess: because it was in a subdirectory called "target" (package was *.target) :smile: 

Btw, I'm checking the commit now and push it if it's fine.

**Comment by agudian** [comment]
OK, I've checked every single file. No headers missed.

FYI, we have the following paths with "target" as directory name:
{code}
./processor/src/test/java/org/mapstruct/ap/test/array/target
./processor/src/test/java/org/mapstruct/ap/test/bugs/_394/target
./processor/src/test/java/org/mapstruct/ap/test/builtin/target
./processor/src/test/java/org/mapstruct/ap/test/collection/adder/target
./processor/src/test/java/org/mapstruct/ap/test/complex/target
./processor/src/test/java/org/mapstruct/ap/test/inheritedmappingmethod/target
./processor/src/test/java/org/mapstruct/ap/test/nestedproperties/simple/target
./processor/src/test/java/org/mapstruct/ap/test/nestedsourceproperties/target
./processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/target
{code}

**Comment by gunnarmorling** [comment]
> OK, I've checked every single file. No headers missed.

Cool, thanks.

> FYI, we havet the following paths with "target" as directory name:

WDYT, should we change those? Seems like the license plug-in doesn't like it, and I vaguely remember a git issue around it as well (don't remember the details, though).

**Comment by agudian** [comment]
> WDYT, should we change those?

We should. I've just created a simple checkstyle-rule to check it. I'll create an issue and a pull-request.

**Pull request closed without merging**
