### PR TITLE
#1924 Correct handling of org.immutables.value.Value.Style.typeImmutable

### PR DESCRIPTION
**Pull request by Drevsh**
Immutables allows adapting the name of the generated classes via `@org.immutables.value.Value.Style`
Also see: https://immutables.github.io/style.html

This PR adds correct handling for prefix/infix/postfix handling.
Example: 
```
@Value.Immutable
@Value.Style(defaultAsDefault = true, typeImmutable = "_*_")
public interface NotificationMessageDtoInifx {
	String getMessage();
	String getTableId();
	String getType();
}

@Value.Immutable
@Value.Style(defaultAsDefault = true, typeImmutable = "*_")
public interface NotificationMessageDtoPostfix {
	String getMessage();
	String getTableId();
	String getType();
}

@Value.Immutable
@Value.Style(defaultAsDefault = true, typeImmutable = "_*")
public interface NotificationMessageDtoPrefix {
	String getMessage();
	String getTableId();
	String getType();
}
```

Now results in the correct Builder:
```
public class MessageMapperInfixImpl implements MessageMapperInfix {

    @Override
    public NotificationMessageDto map(NotificationMessageInfix msg) {
        if ( msg == null ) {
            return null;
        }

        _NotificationMessageDto_.Builder notificationMessageDto = _NotificationMessageDto_.builder();

        notificationMessageDto.message( msg.getMessage() );
        notificationMessageDto.tableId( msg.getTableId() );
        notificationMessageDto.type( msg.getType() );

        return notificationMessageDto.build();
    }
}

public class MessageMapperPostfixImpl implements MessageMapperPostfix {

    @Override
    public NotificationMessageDto map(NotificationMessagePostfix msg) {
        if ( msg == null ) {
            return null;
        }

        NotificationMessageDto_.Builder notificationMessageDto = NotificationMessageDto_.builder();

        notificationMessageDto.message( msg.getMessage() );
        notificationMessageDto.tableId( msg.getTableId() );
        notificationMessageDto.type( msg.getType() );

        return notificationMessageDto.build();
    }
}

public class MessageMapperPrefixImpl implements MessageMapperPrefix {

    @Override
    public NotificationMessageDto map(NotificationMessagePrefix msg) {
        if ( msg == null ) {
            return null;
        }

        _NotificationMessageDto.Builder notificationMessageDto = _NotificationMessageDto.builder();

        notificationMessageDto.message( msg.getMessage() );
        notificationMessageDto.tableId( msg.getTableId() );
        notificationMessageDto.type( msg.getType() );

        return notificationMessageDto.build();
    }
}
```

### CODE REVIEW

**Comment by sleicht** [comment]
Thanks for this improved handling of immutables. I created out of your examples some IT cases: https://github.com/sleicht/mapstruct/commit/ed826f39550db8a442305adae2922f99c3a512e1

**Comment by Drevsh** [comment]
Nice I could not find the correct integration test (where I would have had access to the immutables annotations). 
Will add them to the PR first thin tomorrow.

**Comment by Drevsh** [comment]
Could you give me a hint on how to setup the integration tests correctly? I'm unable to correctly import the tests. I tried to import them via Eclipse and Intelij but both IDEs seem to struggle with the project hierarchy... and having the tests in the resource folder

**Comment by sleicht** [comment]
Unfortunately I did not find a documentation how to do it "the right way". So I had to fiddle around a little bit.
After applying this [patch](https://gist.github.com/sleicht/ce3c0110e52e95f728500dc2d33261d9) you can import the folder `integrationtest/src/test/resources/immutablesBuilderTest` into intellij. With those further steps I could then run the 'ImmutablesMapperTest' in IntelliJ:

In Terminal:
- `cd <project_root>/integrationtest/src/test/resources/immutablesBuilderTest`
- `mvn clean compile -P generate-via-compiler-plugin`

**Pull request closed without merging**
