### PR TITLE
Issue 603

### PR DESCRIPTION
**Pull request by bedla**
Hi, I have created Pull request for  issue #603 . First commit is about refactoring test-utils to seperated module and moving processor-tests into own module.
Second commit dependent on first commit and filters out statis and default methods from interface. Third commit is about refactoring classes from upstream to honour changes from first commit.
Hope you will like it.
Ivos

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Many thanks, Ivo! Going to look at it soon.

**Comment by gunnarmorling** [comment]
Hey @bedla, what's the motivation for moving all the tests into a separate module? I think it's a good practice to have tests close to the code they test, i.e. in the same module.

**Comment by agudian** [comment]
The "only" problem is source/target type 1.6 in the processor-module, right? Maven-wise, we could use different configurations for main and test compilation, but the IDEs would get in trouble then.

Still, I would also favour keeping the tests in the same module. Until we start doing any fancy stuff with default methods, we could just rely on the Java 8 integration test (see Java8Test and src/test/resources/java8Test/... in the integration-test module). Running it in the IDE requires you to `mvn install` the processor module first, but that should be ok for corner cases like this. (For hints on debugging the integration tests, see http://mapstruct.org/contributing/#section-04).

**Comment by gunnarmorling** [comment]
> Maven-wise, we could use different configurations for main and test compilation, but the IDEs would get in trouble then.

Right, for Maven it should be no problem. What happens when importing that set-up into Eclipse? I am open for giving it a try. If it's not workable then +1 for amending the existing Java 8 test in the integration test module and leaving all others in the processor module as is.

**Comment by bedla** [comment]
Hi, right it is because of Java8 specific syntax - and I agree that it is better to have test close enough to classes they test.
I can revert separation to modules and make test 1.8 compatible in pom.xml... I hope that methods with body are the only one difference between 1.7 and 1.8 syntax.
Ivos

**Comment by bedla** [comment]
I have created test branch without module separation https://github.com/bedla/mapstruct/tree/ISSUE-603-no_module ... It looks ok from Maven perspective, but IntelliJ IDEA is not happy with it because you can set diferent language level per sources and test sources (you can vote for issue here https://youtrack.jetbrains.com/issue/IDEA-85478 ). I dont know how about Eclipse and other editors.

**Comment by agudian** [comment]
> I dont know how about Eclipse and other editors.

Yeah, I don't know about any editor that can currently do it. But thanks for trying it out! If it worked with IntelliJ, then I would have added a tweak to switch to complete Java 8 in Eclipse "automatically". But we shouldn't go down that path then...

So I'd suggest extending the Java8Test project in the integrationtest-module, as discussed above... :-/ 

What do you think?

**Comment by bedla** [comment]
Fixed typo in prev comment :)

Anyways I can extend Java8Test, it looks good for now. Would you like to create new Pull request? Or I can force push this/my remote branch... :]

Ivos

**Comment by agudian** [comment]
Great, please just do the force-push to the existing remote. :+1:

**Comment by bedla** [comment]
Branch updated :-)

**Comment by agudian** [comment]
Looks great! 
If you could just remove the compiler-config in the processor/pom.xml again and squash all your commits into one, I'll merge it to master tonight. :-)

**Comment by bedla** [comment]
Done :-)

**Comment by agudian** [comment]
@bedla merged it and I've added you to the list of contributors. Again, many thanks for your work and for your patience with us! Feel free to send us more stuff any time you like :wink:.

**Comment by gunnarmorling** [comment]
Thanks, guys!

**Comment by bedla** [comment]
No problem. It is pleasure to work on project like this.
Ivos

**Pull request merged**
