### PR TITLE
fix: #2825 SubclassMapping stackoverflow exception

### PR DESCRIPTION
**Pull request by chenzijia12300**
fix [SubclassMapping stackoverflow exception](https://github.com/mapstruct/mapstruct/issues/2825)

### CODE REVIEW

**Review by filiphr — COMMENTED** [review]
Thanks for working on this @chenzijia12300. I'll need to check it out locally, as I am not sure that the fix in the `MappingResolverImpl` is the right one.

**Review by filiphr — CHANGES_REQUESTED** [review]
@chenzijia12300 I've adapted the change that is needed to fix this.

Can you perhaps explain it my why we need so many mappers in the tests? Isn't it enough to only have the `AnimalMapper` for this issue?

**Comment by chenzijia12300** [comment]
Sorry for submitting more than one useless test class, I added multiple mappers at that time to better debug the logic of ResolvingAttempt class

**Comment by filiphr** [comment]
>Sorry for submitting more than one useless test class, I added multiple mappers at that time to better debug the logic of ResolvingAttempt class

No need to apologise, I was only being curious. I've pushed a commit that removes the extra test classes. Will merge once the CI is done

**Pull request merged**
