### PR TITLE
#1384 Put AstModifyingAnnotationProcessor in a separate module for reuse by Lombok and the likes

### PR DESCRIPTION
**Pull request by sjaakd**
@filiphr @gunnarmorling ..trying ot isolate the `AstModifyingProcessor` into a separate maven module. Like requested in #1384 

Questions.
1. what kind of dependency scope should I use? Provided / Compile?
2. I only did the `AstModifyingProcessor`.. I reckon the remainder stays in the processor.
3. I'm struggling with the unit test. Do not understand why there's a difference between the annotations which seems to be on the class path directly in contrast to the new `astmodifying-spi'  module, which seems to be there only as maven dependency.. 
4. Is this what you think should be done?

### CODE REVIEW

**Comment by sjaakd** [comment]
@agudian .. You are familiar with the test helper classes.. How do I get this new MapStruct submodule on the class path directly (not as maven dependency) like the MapStruct core (api) packages? It is not in the list that's filtered.

**Comment by filiphr** [comment]
@sjaakd I think that the magic happens in [`CompilingStatement#buildProcessorClasspath`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingStatement.java#L149)

As for the other questions:

1. It should be compile as we depend on it non optionally
1. I would say that only the `AstModifyingProcessor` should be moved
1. The tests are failing because the `AstModifyingProcessor` is not on the processor path. See my reply above
1. The `AstModifyingProcessor` can't stay in the same package, as that is not allowed by JPMS. We need to think what the best approach for this would be. Maybe it needs to go into a repo of it's own

**Comment by sjaakd** [comment]
> @sjaakd I think that the magic happens in CompilingStatement#buildProcessorClasspath

Tried that.. but its only white-listing.. See my question to @agudian . So an already existing class path is filtered on your referred lines. But how does it get on the class path in the first place? Its not the maven dependency mechanism, that gives the current result..  Just place a breakpoint and see how the core listed in contrast to the API.

> It should be compile as we depend on it non optionally

OK. 



> The AstModifyingProcessor can't stay in the same package, as that is not allowed by JPMS. We need to think what the best approach for this would be. Maybe it needs to go into a repo of it's own

Did not know that.. I should get familiar with java9.

**Comment by sjaakd** [comment]
> @sjaakd I think that the magic happens in CompilingStatement#buildProcessorClasspath

Now it works.. Tried it several times before.. strange..

**Comment by filiphr** [comment]
@sjaakd I am not sure what the correct way of doing this is. If we move the package people will have to update to a new Lombok that would have this update. On top of that, I don't think that we need to have this module in the mapstruct repository. We should extract it out if possible.

I am not entirely sure about the package name as well. As this is not really an integration with MapStruct, but it is more about APT that are not according to the spec, so we just invoke implementations of it. 

This change has to be done in sync with the Lombok team.

There is one way to achieve a good way for this and that is to make the current `AstModifyingProcessor` deprecated and extend from the new one. This way we can get all implementations of the new SPI (not sure how this actually works as SPIs are defined in META-INF, so we might need to get both the old and the new SPI

**Comment by sjaakd** [comment]
> We should extract it out if possible.

I'm not sure whether its worthwhile to call a new organisation into existence in GitHub. But we could use a personal GitHub account to do so (believe, if I recollect correctly, Lombok is [on a personal GitHub account](https://github.com/rzwitserloot/lombok). So we might move it out to yours or mine user account.

**Comment by filiphr** [comment]
We don't need a new organization. It can be part of the mapstruct organization, but new repository. Just like the plugins and examples we have

**Comment by sjaakd** [comment]
> We don't need a new organization. It can be part of the mapstruct organization, but new repository. Just like the plugins and examples we have

i was thinking: if its true integration functionality... its perhaps better to entirely decouple it from MapStruct. Anyway .. that's more like a psychological thing..

**Comment by sjaakd** [comment]
> This way we can get all implementations of the new SPI (not sure how this actually works as SPIs are defined in META-INF, so we might need to get both the old and the new SPI

I reckon you have to load both of them.. the deprecated one and the new one. The extension only takes care of being able to write the handling code efficiently. But then again.. its a couple of lines where the `AstModifyingAnnotationProcessor ` is actually used

**Comment by sjaakd** [comment]
I leave this one for the time being....

**Comment by sjaakd** [comment]
Ok.. still need to add some integration test to see whether this flies.

**Pull request closed without merging**
