### PR TITLE
#1591 Fix LocalDateTime conversion from UTC to use the local timezone

### PR DESCRIPTION
**Pull request by sivviswa22**

### CODE REVIEW

**Comment by sivviswa22** [comment]
@filiphr Please review.

**Comment by filiphr** [comment]
@sivviswa22 this PR is not linked with the #1591. What exactly are you trying to achieve? Using the UTC zone is by design it is not a bug

**Comment by sivviswa22** [comment]
But should we be not just be mapping the date time to LocalDateTime and vice-versa to exactly the same timezone values instead of formatting/converting it to UTC?

> @sivviswa22 this PR is not linked with the #1591. What exactly are you trying to achieve? Using the UTC zone is by design it is not a bug

But should we be not just be mapping the date time to LocalDateTime and vice-versa to exactly the same timezone values instead of formatting/converting it to UTC?

**Comment by sivviswa22** [comment]
Closing this pull request will create a new one with the correct changes.

**Pull request closed without merging**
